name: Runner IP

on:
  workflow_dispatch:

permissions: {}

jobs:
  runner-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Get public IP address
        run: |
          public_ip=$(curl --fail --silent --show-error https://api.ipify.org)
          echo "Public IP: $public_ip"
